title: Góc Truyện Nhỏ
email: thanhho1356@gmail.com
description: So many books, so little time.
url: "https://trieulm-2.github.io"
baseurl: "/goctruyencuatui"
remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
markdown: kramdown